In [1]:
pwd

'C:\\Users\\rambu\\Python Scripts\\Milestone_3\\docker-project-template\\ift6758\\ift6758\\client'

In [2]:
from game_client import get_df_by_game

In [3]:
df = get_df_by_game(2025020001)
df.shape

Fetched 2025020001
2025020001 is NOT LIVE

(82, 42)

In [4]:
df.head(1)

,game_id,season,game_type,game_outcome,game_state,period_number,period_type,time_in_period,strength,event_type,...,away_score,venue,venue_location,is_goal,empty_net,x_mean_home,x_distance,distance_net,angle_deg,angle_rad
0,2025020001,20252026,2,REG,OFF,1,REG,01:16,NaN,shot-on-goal,...,2,Amerant Bank Arena,Sunrise,0,0,-61.0,31,38.013156,35.362462,0.617191

In [9]:
df = get_df_by_game(2025020377)
df.shape

Fetched 2025020377
2025020377 is LIVE

(32, 42)

In [17]:
live_df = get_df_by_game(2025020377)
live_df.shape

Fetched 2025020377
2025020377 is LIVE

(35, 42)

In [15]:
df.tail(3)

,game_id,season,game_type,game_outcome,game_state,period_number,period_type,time_in_period,strength,event_type,...,away_score,venue,venue_location,is_goal,empty_net,x_mean_home,x_distance,distance_net,angle_deg,angle_rad
29,2025020377,20252026,2,NaN,LIVE,1,REG,19:35,NaN,missed-shot,...,2,Little Caesars Arena,Detroit,0,0,-67.266667,9,24.698178,68.629378,1.197809
30,2025020377,20252026,2,NaN,LIVE,1,REG,19:50,NaN,shot-on-goal,...,2,Little Caesars Arena,Detroit,0,0,-67.266667,22,22.803509,15.255119,0.266252
31,2025020377,20252026,2,NaN,LIVE,2,REG,00:34,NaN,goal,...,2,Little Caesars Arena,Detroit,1,0,NaN,15,15.132746,7.594643,0.132552

In [18]:
live_df.tail(5)

,game_id,season,game_type,game_outcome,game_state,period_number,period_type,time_in_period,strength,event_type,...,away_score,venue,venue_location,is_goal,empty_net,x_mean_home,x_distance,distance_net,angle_deg,angle_rad
30,2025020377,20252026,2,NaN,LIVE,1,REG,19:50,NaN,shot-on-goal,...,2,Little Caesars Arena,Detroit,0,0,-67.266667,22,22.803509,15.255119,0.266252
31,2025020377,20252026,2,NaN,LIVE,2,REG,00:34,NaN,goal,...,2,Little Caesars Arena,Detroit,1,0,61.333333,15,15.132746,7.594643,0.132552
32,2025020377,20252026,2,NaN,LIVE,2,REG,00:59,NaN,missed-shot,...,2,Little Caesars Arena,Detroit,0,0,61.333333,24,32.557641,42.510447,0.741947
33,2025020377,20252026,2,NaN,LIVE,2,REG,01:01,NaN,shot-on-goal,...,2,Little Caesars Arena,Detroit,0,0,61.333333,3,3.605551,33.690068,0.588003
34,2025020377,20252026,2,NaN,LIVE,2,REG,02:26,NaN,shot-on-goal,...,2,Little Caesars Arena,Detroit,0,0,61.333333,56,56.320511,6.115504,0.106736