In [1]:
pwd

'C:\\Users\\rambu\\Python Scripts\\Milestone_3\\docker-project-template\\ift6758\\ift6758\\client'

In [2]:
from game_client import get_df_by_game
from serving_client import ServingClient

In [3]:
df = get_df_by_game(2025020001)
df.shape

Fetched 2025020001
2025020001 is NOT LIVE

(82, 42)

In [4]:
df.head(1)

,game_id,season,game_type,game_outcome,game_state,period_number,period_type,time_in_period,strength,event_type,...,away_score,venue,venue_location,is_goal,empty_net,x_mean_home,x_distance,distance_net,angle_deg,angle_rad
0,2025020001,20252026,2,REG,OFF,1,REG,01:16,NaN,shot-on-goal,...,2,Amerant Bank Arena,Sunrise,0,0,-61.0,31,38.013156,35.362462,0.617191

In [4]:
df = get_df_by_game(2025020377)
df.shape

Fetched 2025020377
2025020377 is NOT LIVE

(89, 42)

In [5]:
live_df = get_df_by_game(2025020377)
live_df.shape

Fetched 2025020377
2025020377 is NOT LIVE

(89, 42)

In [6]:
df.tail(3)

,game_id,season,game_type,game_outcome,game_state,period_number,period_type,time_in_period,strength,event_type,...,away_score,venue,venue_location,is_goal,empty_net,x_mean_home,x_distance,distance_net,angle_deg,angle_rad
86,2025020377,20252026,2,REG,OFF,3,REG,17:13,NaN,goal,...,6,Little Caesars Arena,Detroit,1,1,-67.466667,39,44.777226,29.427456,0.513606
87,2025020377,20252026,2,REG,OFF,3,REG,18:39,NaN,shot-on-goal,...,6,Little Caesars Arena,Detroit,0,0,-67.466667,21,35.805028,54.090277,0.944053
88,2025020377,20252026,2,REG,OFF,3,REG,19:47,NaN,shot-on-goal,...,6,Little Caesars Arena,Detroit,0,0,-67.466667,8,10.630146,41.185925,0.718830

In [7]:
live_df.tail(5)

,game_id,season,game_type,game_outcome,game_state,period_number,period_type,time_in_period,strength,event_type,...,away_score,venue,venue_location,is_goal,empty_net,x_mean_home,x_distance,distance_net,angle_deg,angle_rad
84,2025020377,20252026,2,REG,OFF,3,REG,17:04,NaN,missed-shot,...,6,Little Caesars Arena,Detroit,0,0,-67.466667,5,35.355339,81.869898,1.428899
85,2025020377,20252026,2,REG,OFF,3,REG,17:05,NaN,shot-on-goal,...,6,Little Caesars Arena,Detroit,0,0,-67.466667,7,8.062258,29.744881,0.519146
86,2025020377,20252026,2,REG,OFF,3,REG,17:13,NaN,goal,...,6,Little Caesars Arena,Detroit,1,1,-67.466667,39,44.777226,29.427456,0.513606
87,2025020377,20252026,2,REG,OFF,3,REG,18:39,NaN,shot-on-goal,...,6,Little Caesars Arena,Detroit,0,0,-67.466667,21,35.805028,54.090277,0.944053
88,2025020377,20252026,2,REG,OFF,3,REG,19:47,NaN,shot-on-goal,...,6,Little Caesars Arena,Detroit,0,0,-67.466667,8,10.630146,41.185925,0.718830

In [8]:
col = ['distance_net']
send_df = df[col]
send_df.shape

(89, 1)

In [9]:
serving_cl = ServingClient()

In [15]:
preds = serving_cl.predict(send_df)
len(preds)

89

In [16]:
preds

[0.021492679241747848,
 0.025801110377253026,
 0.02990805811181983,
 0.04626793738891196,
 0.14721269769982628,
 0.009153177538546236,
 0.09298668362211095,
 0.10720119727139678,
 0.061718663863026525,
 0.12434177142829098,
 0.07418510601935849,
 0.022866205467711495,
 0.11752099875603506,
 0.040751401956402804,
 0.13869474897461634,
 0.026052659104947605,
 0.08899844784566824,
 0.07159134640536897,
 0.10418099645926844,
 0.02257813135055643,
 0.0664483719822625,
 0.06749283878862362,
 0.13869474897461634,
 0.04173898821515528,
 0.05343464464098005,
 0.06094958873254778,
 0.044266260808485766,
 0.08089866747737248,
 0.05585691097195997,
 0.08180643829486939,
 0.08671401694275542,
 0.10940174941271881,
 0.0640465614446209,
 0.15318845934235628,
 0.029890762620472053,
 0.13092526902214924,
 0.1347665379181843,
 0.13501048295388973,
 0.09333334511855047,
 0.15318845934235628,
 0.07839593513742192,
 0.09032378706973264,
 0.13135037374528963,
 0.03720246130090489,
 0.0009839433851645228,
 0.04048610889256582,
 0.03557492573649624,
 0.1381340024968284,
 0.06749283878862362,
 0.07707140146159654,
 0.1378583746650689,
 0.051585402149381857,
 0.07038106466124866,
 0.10003264433511261,
 0.06467054689056324,
 0.06364710307791376,
 0.15660414687259572,
 0.1417163284124687,
 0.1347665379181843,
 0.05379159083491962,
 0.05066178134247985,
 0.05735627981535238,
 0.05463341527807127,
 0.08180643829486939,
 0.03710562673390818,
 0.026158541880782513,
 0.02910292518942798,
 0.052928802549895806,
 0.038205949727051436,
 0.13113701908338846,
 0.09278022571906636,
 0.044266260808485766,
 0.029227859984721945,
 0.03669849814966448,
 0.0806009979772931,
 0.1389800583829757,
 0.07143776538667368,
 0.04803666846718379,
 0.023416378872944687,
 0.13869474897461634,
 0.1444652905210652,
 0.05735627981535238,
 0.1250252459148459,
 0.09676035797635225,
 0.05864070558391834,
 0.1347665379181843,
 0.0434275869221795,
 0.0578127154324993,
 0.1250252459148459]