In [1]:
pwd

'C:\\Users\\rambu\\Python Scripts\\Milestone_3\\docker-project-template\\ift6758\\ift6758\\client'

In [2]:
from game_client import get_df_by_game
from serving_client import ServingClient

In [3]:
df = get_df_by_game(2025020001)
df.shape

Fetched 2025020001
2025020001 is NOT LIVE

(82, 42)

In [4]:
df.head(1)

,game_id,season,game_type,game_outcome,game_state,period_number,period_type,time_in_period,strength,event_type,...,away_score,venue,venue_location,is_goal,empty_net,x_mean_home,x_distance,distance_net,angle_deg,angle_rad
0,2025020001,20252026,2,REG,OFF,1,REG,01:16,NaN,shot-on-goal,...,2,Amerant Bank Arena,Sunrise,0,0,-61.0,31,38.013156,35.362462,0.617191

In [5]:
df = get_df_by_game(2025020377)
df.shape

Fetched 2025020377
2025020377 is NOT LIVE

(89, 42)

In [6]:
live_df = get_df_by_game(2025020377)
live_df.shape

Fetched 2025020377
2025020377 is NOT LIVE

(89, 42)

In [7]:
df.tail(3)

,game_id,season,game_type,game_outcome,game_state,period_number,period_type,time_in_period,strength,event_type,...,away_score,venue,venue_location,is_goal,empty_net,x_mean_home,x_distance,distance_net,angle_deg,angle_rad
86,2025020377,20252026,2,REG,OFF,3,REG,17:13,NaN,goal,...,6,Little Caesars Arena,Detroit,1,1,-67.466667,39,44.777226,29.427456,0.513606
87,2025020377,20252026,2,REG,OFF,3,REG,18:39,NaN,shot-on-goal,...,6,Little Caesars Arena,Detroit,0,0,-67.466667,21,35.805028,54.090277,0.944053
88,2025020377,20252026,2,REG,OFF,3,REG,19:47,NaN,shot-on-goal,...,6,Little Caesars Arena,Detroit,0,0,-67.466667,8,10.630146,41.185925,0.718830

In [8]:
live_df.tail(1)

,game_id,season,game_type,game_outcome,game_state,period_number,period_type,time_in_period,strength,event_type,...,away_score,venue,venue_location,is_goal,empty_net,x_mean_home,x_distance,distance_net,angle_deg,angle_rad
88,2025020377,20252026,2,REG,OFF,3,REG,19:47,NaN,shot-on-goal,...,6,Little Caesars Arena,Detroit,0,0,-67.466667,8,10.630146,41.185925,0.71883

In [9]:
col = ['distance_net']
send_df = df[col]
send_df.shape

(89, 1)

In [10]:
serving_cl = ServingClient()

In [11]:
preds = serving_cl.predict(send_df)
len(preds)

89

In [13]:
preds[:5]

[0.021492679241747848,
 0.025801110377253026,
 0.02990805811181983,
 0.04626793738891196,
 0.14721269769982628]

In [15]:
logs = serving_cl.logs()
len(logs)

1