In [1]:
pwd

'C:\\Users\\rambu\\Python Scripts\\Milestone_3\\docker-project-template\\ift6758\\ift6758\\client'

In [2]:
from game_client import get_df_by_game
from serving_client import ServingClient

In [ ]:
df = get_df_by_game(2025020001)
df.shape

In [ ]:
df.head(1)

In [3]:
df = get_df_by_game(2025020001)
df.shape

Fetched 2025020001
2025020001 is NOT LIVE

(82, 42)

In [27]:
df.tail(1)

,game_id,season,game_type,game_outcome,game_state,period_number,period_type,time_in_period,strength,event_type,...,away_score,venue,venue_location,is_goal,empty_net,x_mean_home,x_distance,distance_net,angle_deg,angle_rad
81,2025020001,20252026,2,REG,OFF,3,REG,19:24,NaN,missed-shot,...,2,Amerant Bank Arena,Sunrise,0,0,-65.428571,20,28.284271,45.0,0.785398

In [15]:
col = ['distance_net']
send_df = df[col]
send_df.shape, send_df.columns

((82, 1), Index(['distance_net'], dtype='object'))

In [16]:
serving_cl = ServingClient()

Serving Client Initialized

In [17]:
model = serving_cl.download_registry_model(workspace = "IFT6758-2025-A10/Logistic Regression",
                                          model = "Distance", version="v1")

Model switched to: IFT6758-2025-A10/Logistic Regression/Distance:v1

In [18]:
preds = serving_cl.predict(send_df)
len(preds)

82

In [19]:
preds[:5]

[0.053904002483522555,
 0.027268441835609215,
 0.04355248832000983,
 0.02380623900354608,
 0.020327621750744224]

In [20]:
logs = serving_cl.logs()
len(logs)

1

In [21]:
col_angle = ['angle_rad']
send_df = df[col_angle]

In [22]:
#Switch model to angle first
model = serving_cl.download_registry_model(workspace = "IFT6758-2025-A10/Logistic Regression",
                                          model = "Angle", version="v1")

Model switched to: IFT6758-2025-A10/Logistic Regression/Angle:v1

In [23]:
preds = serving_cl.predict(send_df)
preds[:5]

[0.06526414286292434,
 0.0743880439542011,
 0.06268016309635639,
 0.06732420217466013,
 0.06811276812640266]

In [24]:
#Switch model to angle and distance first
model = serving_cl.download_registry_model(workspace = "IFT6758-2025-A10/Logistic Regression",
                                          model = "Distance_Angle", version="v1")

Model switched to: IFT6758-2025-A10/Logistic Regression/Distance_Angle:v1

In [25]:
col_dist_angle=['distance_net','angle_rad']
send_df = df[col_dist_angle]

In [26]:
preds = serving_cl.predict(send_df)
preds[:5]

[0.0494822906194551,
 0.029476340472745974,
 0.03719424315145171,
 0.0219367077339118,
 0.0189151721227029]

### Live Game Test = Id: 2025020383 mtl Canadien v/s vegas golden knights

In [29]:
live_df_1 = get_df_by_game(2025020383)
live_df_1.shape

Fetched 2025020383
2025020383 is LIVE

(53, 42)

In [36]:
live_df_2 = get_df_by_game(2025020383)
live_df_2.shape

Fetched 2025020383
2025020383 is LIVE

(61, 42)

In [37]:
live_df_2.tail(5)

,game_id,season,game_type,game_outcome,game_state,period_number,period_type,time_in_period,strength,event_type,...,away_score,venue,venue_location,is_goal,empty_net,x_mean_home,x_distance,distance_net,angle_deg,angle_rad
56,2025020383,20252026,2,NaN,LIVE,2,REG,15:36,NaN,missed-shot,...,2,T-Mobile Arena,Paradise,0,0,58.2,21,28.319605,42.137595,0.735440
57,2025020383,20252026,2,NaN,LIVE,2,REG,16:44,NaN,shot-on-goal,...,2,T-Mobile Arena,Paradise,0,0,58.2,26,30.528675,31.607502,0.551655
58,2025020383,20252026,2,NaN,LIVE,2,REG,16:54,NaN,missed-shot,...,2,T-Mobile Arena,Paradise,0,0,58.2,35,36.400549,15.945396,0.278300
59,2025020383,20252026,2,NaN,LIVE,2,REG,17:41,NaN,missed-shot,...,2,T-Mobile Arena,Paradise,0,0,58.2,13,26.419690,60.524111,1.056345
60,2025020383,20252026,2,NaN,LIVE,2,REG,19:09,NaN,shot-on-goal,...,2,T-Mobile Arena,Paradise,0,0,58.2,19,19.416488,11.888658,0.207496

In [30]:
#Switch model to angle and distance first
model = serving_cl.download_registry_model(workspace = "IFT6758-2025-A10/Logistic Regression",
                                          model = "Distance_Angle", version="v1")

Model switched to: IFT6758-2025-A10/Logistic Regression/Distance_Angle:v1

In [47]:
col_dist_angle=['distance_net','angle_rad']
send_df = live_df_1[col_dist_angle]

In [48]:
live_preds = serving_cl.predict(send_df)
live_preds[:5], live_preds[-5:]

([0.049769427659781845,
  0.009504504582758592,
  0.0409357905266797,
  0.02634245568409006,
  0.0436312218121691],
 [0.11536782699433411,
  0.05958510287608438,
  0.06152479254053798,
  0.11419422346002737,
  0.09444550582784202])

In [51]:
col_dist_angle=['distance_net','angle_rad']
send_df = live_df_2[col_dist_angle]

live_preds_2 = serving_cl.predict(send_df)
live_preds_2[-13:]

[0.11536782699433411,
 0.05958510287608438,
 0.06152479254053798,
 0.11419422346002737,
 0.09444550582784202,
 0.09659492595024743,
 0.018613852410666272,
 0.043317038563830366,
 0.0631179950080255,
 0.06628689958155896,
 0.06547183376636796,
 0.05427005738666233,
 0.11819033420096652]