In [1]:
pwd

'C:\\Users\\rambu\\Python Scripts\\Milestone_3\\docker-project-template\\ift6758\\ift6758\\client'

In [2]:
from game_client import get_df_by_game

In [3]:
df = get_df_by_game(2025020001)
df.shape

Fetched 2025020001
2025020001 is NOT LIVE

(82, 42)

In [4]:
df.head(1)

,game_id,season,game_type,game_outcome,game_state,period_number,period_type,time_in_period,strength,event_type,...,away_score,venue,venue_location,is_goal,empty_net,x_mean_home,x_distance,distance_net,angle_deg,angle_rad
0,2025020001,20252026,2,REG,OFF,1,REG,01:16,NaN,shot-on-goal,...,2,Amerant Bank Arena,Sunrise,0,0,-61.0,31,38.013156,35.362462,0.617191

In [3]:
df = get_df_by_game(2025020377)
df.shape

Fetched 2025020377
2025020377 is LIVE

(31, 42)

In [ ]:
df = get_df_by_game(2025020377)
df.shape

In [5]:
df.head(2)

,game_id,season,game_type,game_outcome,game_state,period_number,period_type,time_in_period,strength,event_type,...,away_score,venue,venue_location,is_goal,empty_net,x_mean_home,x_distance,distance_net,angle_deg,angle_rad
0,2025020377,20252026,2,NaN,LIVE,1,REG,00:28,NaN,shot-on-goal,...,1,Little Caesars Arena,Detroit,0,0,-67.266667,53,66.400301,37.042475,0.646513
1,2025020377,20252026,2,NaN,LIVE,1,REG,00:32,NaN,shot-on-goal,...,1,Little Caesars Arena,Detroit,0,0,-67.266667,54,60.827625,27.407575,0.478352