In [1]:
pwd

'C:\\Users\\rambu\\Python Scripts\\Milestone_3\\docker-project-template\\ift6758\\ift6758\\client'

In [2]:
from game_client import fetch_data_by_api, get_play_by_play_by_game, get_df_by_game
from feature_eng_1 import get_engineered_df_by_game
import pandas as pd

### Single function call to get engineered_df

In [6]:
#Default id = 2016020001
#df = get_df_by_game()

df = get_df_by_game(2025020015)
df.shape

Fetched 2025020015

(75, 41)

In [7]:
df.head(5)

,game_id,season,game_type,game_outcome,period_number,period_type,time_in_period,strength,event_type,shot_type,...,away_score,venue,venue_location,is_goal,empty_net,x_mean_home,x_distance,distance_net,angle_deg,angle_rad
0,2025020015,20252026,2,REG,1,REG,00:18,NaN,missed-shot,wrist,...,5,Enterprise Center,St. Louis,0,0,59.2,59,66.648331,27.718502,0.483779
1,2025020015,20252026,2,REG,1,REG,02:35,NaN,shot-on-goal,wrist,...,5,Enterprise Center,St. Louis,0,0,59.2,39,52.402290,41.905942,0.731397
2,2025020015,20252026,2,REG,1,REG,02:36,NaN,missed-shot,backhand,...,5,Enterprise Center,St. Louis,0,0,59.2,5,5.830952,30.963757,0.540420
3,2025020015,20252026,2,REG,1,REG,03:04,NaN,shot-on-goal,deflected,...,5,Enterprise Center,St. Louis,0,0,59.2,8,8.000000,0.000000,0.000000
4,2025020015,20252026,2,REG,1,REG,03:47,NaN,shot-on-goal,wrist,...,5,Enterprise Center,St. Louis,0,0,59.2,55,66.850580,34.640948,0.604599

In [8]:
df.tail(5)

,game_id,season,game_type,game_outcome,period_number,period_type,time_in_period,strength,event_type,shot_type,...,away_score,venue,venue_location,is_goal,empty_net,x_mean_home,x_distance,distance_net,angle_deg,angle_rad
70,2025020015,20252026,2,REG,3,REG,11:55,NaN,shot-on-goal,tip-in,...,5,Enterprise Center,St. Louis,0,0,64.083333,6,6.324555,18.434949,0.321751
71,2025020015,20252026,2,REG,3,REG,12:35,NaN,shot-on-goal,wrist,...,5,Enterprise Center,St. Louis,0,0,64.083333,54,67.201190,36.528855,0.637549
72,2025020015,20252026,2,REG,3,REG,12:44,NaN,shot-on-goal,slap,...,5,Enterprise Center,St. Louis,0,0,64.083333,60,68.963759,29.538782,0.515549
73,2025020015,20252026,2,REG,3,REG,14:25,NaN,shot-on-goal,wrist,...,5,Enterprise Center,St. Louis,0,0,64.083333,16,28.844410,56.309932,0.982794
74,2025020015,20252026,2,REG,3,REG,16:48,NaN,missed-shot,wrist,...,5,Enterprise Center,St. Louis,0,0,64.083333,47,48.270074,13.172553,0.229904

In [9]:
df.columns

Index(['game_id', 'season', 'game_type', 'game_outcome', 'period_number',
       'period_type', 'time_in_period', 'strength', 'event_type', 'shot_type',
       'x', 'y', 'player_id', 'player_name', 'goalie_id', 'goalie_name',
       'zone_code', 'event_owner_team_id', 'event_owner_team_name', 'home_sog',
       'away_sog', 'home_defending_side', 'home_id', 'home_name',
       'home_location', 'home_abrev', 'home_score', 'away_id', 'away_name',
       'away_location', 'away_abrev', 'away_score', 'venue', 'venue_location',
       'is_goal', 'empty_net', 'x_mean_home', 'x_distance', 'distance_net',
       'angle_deg', 'angle_rad'],
      dtype='object')

### Step-by-step Breakdown of different functions involved

In [10]:
data_dict = fetch_data_by_api(2016020003) #Json file

Fetched 2016020003

In [11]:

list_of_plays = get_play_by_play_by_game(data_dict)

df = pd.DataFrame( list_of_plays )
df.shape

(93, 34)

In [14]:
new_df = get_engineered_df_by_game(df)
new_df.shape

(93, 41)

In [15]:
new_df.head(5)

,game_id,season,game_type,game_outcome,period_number,period_type,time_in_period,strength,event_type,shot_type,...,away_score,venue,venue_location,is_goal,empty_net,x_mean_home,x_distance,distance_net,angle_deg,angle_rad
0,2016020003,20162017,2,REG,1,REG,00:57,NaN,missed-shot,snap,...,4,Rogers Place,Edmonton,0,0,57.166667,53,60.901560,29.511499,0.515073
1,2016020003,20162017,2,REG,1,REG,01:10,NaN,goal,tip-in,...,4,Rogers Place,Edmonton,1,0,57.166667,17,17.000000,0.000000,0.000000
2,2016020003,20162017,2,REG,1,REG,01:45,NaN,shot-on-goal,wrap-around,...,4,Rogers Place,Edmonton,0,0,57.166667,3,7.615773,66.801409,1.165905
3,2016020003,20162017,2,REG,1,REG,01:46,NaN,goal,wrist,...,4,Rogers Place,Edmonton,1,0,57.166667,6,7.810250,39.805571,0.694738
4,2016020003,20162017,2,REG,1,REG,03:26,NaN,missed-shot,slap,...,4,Rogers Place,Edmonton,0,0,57.166667,56,56.222771,5.102165,0.089050

In [16]:
new_df.columns

Index(['game_id', 'season', 'game_type', 'game_outcome', 'period_number',
       'period_type', 'time_in_period', 'strength', 'event_type', 'shot_type',
       'x', 'y', 'player_id', 'player_name', 'goalie_id', 'goalie_name',
       'zone_code', 'event_owner_team_id', 'event_owner_team_name', 'home_sog',
       'away_sog', 'home_defending_side', 'home_id', 'home_name',
       'home_location', 'home_abrev', 'home_score', 'away_id', 'away_name',
       'away_location', 'away_abrev', 'away_score', 'venue', 'venue_location',
       'is_goal', 'empty_net', 'x_mean_home', 'x_distance', 'distance_net',
       'angle_deg', 'angle_rad'],
      dtype='object')

### Invalid Id Test

In [19]:
null_df = get_df_by_game(493929) #Returns none

File could not be fetched..Aborted

In [20]:
null_df == None

True